# Generated by Django 5.2 on 2025-05-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(upload_to='static/services/'),
        ),
    ]
