# Generated by Django 5.2 on 2025-05-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_service_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='cover_image',
            new_name='image',
        ),
    ]
