# Generated by Django 5.2 on 2025-05-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_cover_image_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='static/Realization/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.realization'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
