# Generated by Django 5.2 on 2025-05-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realization',
            old_name='image',
            new_name='after_image',
        ),
        migrations.AddField(
            model_name='realization',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/Realization/'),
        ),
    ]
