# Generated by Django 5.2 on 2025-06-20 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_remove_review_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
    ]
